module.exports = ["perfect storm",
"the wrong tree",
"break the ice",
"and a leg",
"of a hat",
"one basket",
"medicine",
"cold shoulder",
"wild goose chase",
"to know one",
"piece of cake",
"cats and dogs",
"with one stone",
"Live and learn",
"On thin ice",
"spill the beans",
"a rain check",
"grain of salt",
"in your court",
"since sliced bread",
"in the details",
"gets the worm",
"whole nine yards",
"in the sea",
"his madness",
"a free lunch",
"to the wind"];